- hosts: local
  connection: local
  gather_facts: False
  vars:
    instance_type: t2.micro
    group:  launch-wizard-2
    image:  ami-dd3c0f36
    keypair: ForNewInstans
    region: eu-central-1
  vars_files:
   - /etc/ansible/aws_keysv2.yml
  tasks:
   - name: make one instance
     ec2: 
          aws_access_key: "{{ ec2_access_key }}"
          aws_secret_key: "{{ ec2_secret_key }}"
          image: "{{ image }}"
          instance_type: "{{ instance_type }}"
          keypair: "{{ keypair }}"
          region: "{{ region }}"
          group: "{{ group }}"
          user_data: |
                     #!/bin/sh
                     sudo yum install python3 -y       
          wait: true
     register: ec2_info
