- hosts: local
  connection: local
  gather_facts: False
  vars:
   instance_type: t2.micro
   group: New
   image: ami-dd3c0f36
   keypair: ForNewInstance1 
   region: eu-central-1
 #vars_files:
 #- /etc/ansible/roles/common/credent.yml
  tasks:
  - name: make one instance
    ec2: 
         aws_access_key: "{{ AWS_ACCESS_KEY }}"
         aws_secret_key: "{{ AWS_SECRET_KEY }}"
         image: "{{ image }}"
         instance_type: "{{ instance_type }}"
         keypair: "{{ keypair }}"
         region: "{{ region }}"
         group: "{{ group }}"
         user_data: |
                    #!/bin/sh
                    sudo yum install python3 -y       
         wait: true
    register: ec2_info
 # - name: Add the newly created EC2 instance(s) to the local host group (located inside the directory)
 #   local_action: lineinfile 
 #                 dest="./hosts" 
 #                 regexp={{ ec2_provision_result.instances }}
 #                 insertafter="[webserver]" line={{ ec2_provision_result.instances }}
                  #regexp={{ item.public_ip }} 
                #  insertafter="[webserver]" line={{ item.public_ip }}
 #   with_items: ec2.instance
